### ISSUE TITLE
Titel für ZMM-Vortrag festlegen

### ISSUE THREAD

**Issue by exot** [fsfw-dresden/medien#12]
Mein aktueller Vorschlag:

    Freie Software und Freie Inhalte für die Schule

Verbesserungsvorschläge?

**Comment by s72785** [comment]
Da mit gerade kein positiver Drogen-Vergleich (als Kontrast zur Kritik am bisherigen Software-Einsatz) einfällt … +1

**Comment by cknoll** [comment]
+0.99

Inhalte ist sehr allgemein. Optionaler Alternativvorschlag:

    Freie Software und Freies Lehrmaterial für die Schule

Ich kann aber mit dem Originalvorschlag sehr gut leben und bin eher dafür den zu nehmen, als noch zu lange über Alternativen zu diskutieren.

**Comment by exot** [comment]
Gefällt mir auch, nehm' ich.
