### ISSUE TITLE
Wikivortrag in eigenes Unterrepo auslagern

### ISSUE THREAD

**Issue by Nos-** [fsfw-dresden/medien#9]
Hallo,

ich habe mal den Wikivortrag aus fsfw-dresden/medien/Wikivortrag in ein eigenes Repo ausgelagert um es besser syncen und wiederverwenden zu können.

Konkret ist das Wikivortrags-Repo nun ein Fork (also eine Ableitung eines anderen Repos). Hierdurch lässt es sich zum einen an vielen verschiedenen Stellen parallel verwenden und die jeweiligen Verbesserungen einfacher und nachvollziehbarer übernehmen.

Es ist nun allerdings etwas ungünstig, das das Wikivortrags-Repo in der Hauptebene rumliegt. Falls sich jemand mit Subrepos auskennt, wäre es bestimmt gut, ihn wieder in einen Ordner oder so zu verfrachten.

**Comment by exot** [comment]
Der Wikivortrag ist jetzt als submodule eingepflegt.
